ldTest run scala.scalanative.junit.ExceptionTest started
ldTest scala.scalanative.junit.ExceptionTest.test started
leTest scala.scalanative.junit.ExceptionTest.test failed: java.lang.IndexOutOfBoundsException: Exception message, took <TIME>
e2scala.scalanative.junit.ExceptionTest.test
ldTest scala.scalanative.junit.ExceptionTest.test finished, took <TIME>
ldTest run scala.scalanative.junit.ExceptionTest finished: 1 failed, 0 ignored, 1 total, <TIME>
d
