liTest run scala.scalanative.junit.ExceptionEverywhere started
leTest scala.scalanative.junit.ExceptionEverywhere failed: java.lang.AssertionError: before class, took <TIME>
e2scala.scalanative.junit.ExceptionEverywhere
leTest scala.scalanative.junit.ExceptionEverywhere failed: java.lang.AssertionError: after class, took <TIME>
liTest run scala.scalanative.junit.ExceptionEverywhere finished: 2 failed, 0 ignored, 0 total, <TIME>
d
